
Description
How To Do Auto Spam With Mobile On YouTube Live Chat || How To Create Free RDP For Mobile Github RDP
158
Likes
5,281
Views
Sep 3
2021
Secret Name: NGROK_AUTH_TOKEN


✓Username: Runneradmin

✓Password: P@ssw0rd!



GitHub Link: https://github.com/


Ngrok Link: https://ngrok.com/

NEW RDP Link :- https://github.com/namikulaufa/rdpngrok

NEW RDP link :- https://github.com/vs454545/WindowsRDP-1

NEW RDP link:- https://github.com/duitawa/NewRDP




Script Link: https://drive.google.com/file/d/1VBXu...


ZEHER Emojis 🤑 Script link:- https://www.pastehere.xyz/beX98Xv1/


App (RD Client) Link: https://play.google.com/store/apps/de...


RDP link: name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/... -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
